# Generated by Django 2.2.14 on 2020-12-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('puesto', models.CharField(max_length=100)),
                ('area_designada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
                ('managers_asignados', models.ManyToManyField(related_name='managers', to='managers.Manager')),
            ],
        ),
    ]
